### ISSUE TITLE
exec-analysis Build error

### ISSUE THREAD

**Issue by kjaeswar76** [Hygieia/ExecDashboard#23]
Getting the below error when we run 

> mvn clean install

in the analysis folder

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  09:06 min
[INFO] Finished at: 2018-11-20T11:05:33Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project exec-analysis: Could not resolve dependencies for project com.capitalone.dashboard:exec-analysis:jar:1.0.0-SNAPSHOT: Could not find artifact com.capitalone.dashboard:exec-core:jar:1.0.0-SNAPSHOT -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

**Comment by kjaeswar76** [comment]
On closer inspection one of the warnings earlier on.. was
[INFO] >>> maven-pmd-plugin:3.6:check (default) > :pmd @ exec-analysis >>>
[WARNING] The POM for com.capitalone.dashboard:exec-core:jar:1.0.0-SNAPSHOT is missing, no dependency information available

**Comment by Sbrenthughes** [comment]
Did you build the core first?

**Comment by Sbrenthughes** [comment]
From the project root directory run `mvn clean install`
