### ISSUE TITLE
EXEC ANALYSIS COLLECTOR (Failed login error)

### ISSUE THREAD

**Issue by Leon-Africa** [Hygieia/ExecDashboard#27]
Hello,

Thanks for the great project.

I have setup the Hygieia Devops Dashboard (https://hygieia.github.io/Hygieia/getting_started.html) and then have the Hygieia Exec Dashboard (https://hygieia.github.io/ExecDashboard/Introduction.html) as well. Both api and ui are deployed for both - collectors in Hygieia Devops are setup and working - now I have the mongodb and collector for the Exec Dashboard as well.

# Property file for execapi:

dbname=execdb
dbhost=mongodbforexec
dbport=27017
dbhostport=mongodbforexec:27017
dbreplicaset=true
dbusername=mongodbforexecuser
dbpassword=mongodbforexecpass
logRequest=true
logSplunkRequest=false
corsEnabled=false
feature.dynamicPipeline=enabled
server.contextPath=/api
server.port=8081
auth.expirationTime=8640000
auth.secret=hygieiasecret
auth.authenticationProviders=STANDARD

# Property file for execcollector:

dbname=execdb
dbhost=mongodbforexec
dbport=27017
dbhostport=mongodbforexec:27017
dbreplicaset=true
dbusername=mongodbforexecuser
dbpassword=mongodbforexecpass

logging.file=/hygieia/logs

portfolio.cron=0 0/30 * * * *
portfolio.readUriUserName=mongodbforhygieidevopsuser
portfolio.readUriPassword=mongodbforhygieidevopspassword
portfolio.readUriDatabase=mongodbforhygieidevops:27017
portfolio.readUriPrefix=mongodb
portfolio.readDatabase=mongodbforhygieidevops
portfolio.writeUri=mongodb://mongodbforexec:27017
portfolio.writeDatabase=mongodbforexec
portfolio.filters=scm-commits:item:environment|production-incidents:severity:4.0|
portfolio.incidentsCollectorFlag=false
portfolio.scmCollectorFlag=true

# Error Log
When the collector runs I am getting this error: (Read from bottom up)

**December 11th 2018, 07:00:00.005 | exec-portfolio-metrics-analysis | java.io.IOException: failure to login
-- | -- | --**

  | December 11th 2018, 07:00:00.005 | exec-portfolio-metrics-analysis | at org.apache.hadoop.security.UserGroupInformation.loginUserFromSubject(UserGroupInformation.java:822) ~[hadoop-common-2.6.5.jar!/:na]

  | December 11th 2018, 07:00:00.005 | exec-portfolio-metrics-analysis | at org.apache.hadoop.security.UserGroupInformation.getLoginUser(UserGroupInformation.java:774) ~[hadoop-common-2.6.5.jar!/:na]

  | December 11th 2018, 07:00:00.005 | exec-portfolio-metrics-analysis | at org.apache.hadoop.security.UserGroupInformation.getCurrentUser(UserGroupInformation.java:647) ~[hadoop-common-2.6.5.jar!/:na]

  | December 11th 2018, 07:00:00.005 | exec-portfolio-metrics-analysis | at org.apache.spark.util.Utils$$anonfun$getCurrentUserName$1.apply(Utils.scala:2430) ~[spark-core_2.11-2.2.0.jar!/:2.2.0]

  | December 11th 2018, 07:00:00.005 | exec-portfolio-metrics-analysis | at org.apache.spark.util.Utils$$anonfun$getCurrentUserName$1.apply(Utils.scala:2430) ~[spark-core_2.11-2.2.0.jar!/:2.2.0]

  | December 11th 2018, 07:00:00.005 | exec-portfolio-metrics-analysis | at scala.Option.getOrElse(Option.scala:121) ~[scala-library-2.11.8.jar!/:na]

  | December 11th 2018, 07:00:00.005 | exec-portfolio-metrics-analysis | at org.apache.spark.util.Utils$.getCurrentUserName(Utils.scala:2430) ~[spark-core_2.11-2.2.0.jar!/:2.2.0]

  | December 11th 2018, 07:00:00.005 | exec-portfolio-metrics-analysis | at org.apache.spark.SparkContext.<init>(SparkContext.scala:295) ~[spark-core_2.11-2.2.0.jar!/:2.2.0]

  | December 11th 2018, 07:00:00.005 | exec-portfolio-metrics-analysis | at org.apache.spark.SparkContext$.getOrCreate(SparkContext.scala:2509) ~[spark-core_2.11-2.2.0.jar!/:2.2.0]

  | December 11th 2018, 07:00:00.005 | exec-portfolio-metrics-analysis | at org.apache.spark.sql.SparkSession$Builder$$anonfun$6.apply(SparkSession.scala:909) ~[spark-sql_2.11-2.2.0.jar!/:2.2.0]

  | December 11th 2018, 07:00:00.005 | exec-portfolio-metrics-analysis | at org.apache.spark.sql.SparkSession$Builder$$anonfun$6.apply(SparkSession.scala:901) ~[spark-sql_2.11-2.2.0.jar!/:2.2.0]

  | December 11th 2018, 07:00:00.005 | exec-portfolio-metrics-analysis | at scala.Option.getOrElse(Option.scala:121) ~[scala-library-2.11.8.jar!/:na]

  | December 11th 2018, 07:00:00.005 | exec-portfolio-metrics-analysis | at org.apache.spark.sql.SparkSession$Builder.getOrCreate(SparkSession.scala:901) ~[spark-sql_2.11-2.2.0.jar!/:2.2.0]

  | December 11th 2018, 07:00:00.005 | exec-portfolio-metrics-analysis | at com.capitalone.dashboard.exec.collector.HygieiaSparkConnection.getInstance(HygieiaSparkConnection.java:28) ~[classes!/:1.0.0-SNAPSHOT]

  | December 11th 2018, 07:00:00.005 | exec-portfolio-metrics-analysis | at com.capitalone.dashboard.exec.collector.PortfolioCollector.collect(PortfolioCollector.java:89) ~[classes!/:1.0.0-SNAPSHOT]

  | December 11th 2018, 07:00:00.005 | exec-portfolio-metrics-analysis | at com.capitalone.dashboard.exec.collector.PortfolioCollector.run(PortfolioCollector.java:301) ~[classes!/:1.0.0-SNAPSHOT]

  | December 11th 2018, 07:00:00.005 | exec-portfolio-metrics-analysis | at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-5.0.2.RELEASE.jar!/:5.0.2.RELEASE]

  | December 11th 2018, 07:00:00.005 | exec-portfolio-metrics-analysis | at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:93) [spring-context-5.0.2.RELEASE.jar!/:5.0.2.RELEASE]

  | December 11th 2018, 07:00:00.005 | exec-portfolio-metrics-analysis | at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_181]

  | December 11th 2018, 07:00:00.005 | exec-portfolio-metrics-analysis | at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_181]

  | December 11th 2018, 07:00:00.005 | exec-portfolio-metrics-analysis | at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_181]

  | December 11th 2018, 07:00:00.005 | exec-portfolio-metrics-analysis | at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_181]

  | December 11th 2018, 07:00:00.005 | exec-portfolio-metrics-analysis | at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_181]

  | December 11th 2018, 07:00:00.005 | exec-portfolio-metrics-analysis | at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_181]

  | December 11th 2018, 07:00:00.005 | exec-portfolio-metrics-analysis | at java.lang.Thread.run(Thread.java:748) [na:1.8.0_181]

  | December 11th 2018, 07:00:00.005 | exec-portfolio-metrics-analysis | **Caused by: javax.security.auth.login.LoginException: java.lang.NullPointerException: invalid null input: name**

  | December 11th 2018, 07:00:00.005 | exec-portfolio-metrics-analysis | at com.sun.security.auth.UnixPrincipal.<init>(UnixPrincipal.java:71)

  | December 11th 2018, 07:00:00.005 | exec-portfolio-metrics-analysis | at com.sun.security.auth.module.UnixLoginModule.login(UnixLoginModule.java:133)

  | December 11th 2018, 07:00:00.005 | exec-portfolio-metrics-analysis | at sun.reflect.GeneratedMethodAccessor33.invoke(Unknown Source)

  | December 11th 2018, 07:00:00.005 | exec-portfolio-metrics-analysis | at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

  | December 11th 2018, 07:00:00.005 | exec-portfolio-metrics-analysis | at java.lang.reflect.Method.invoke(Method.java:498)

  | December 11th 2018, 07:00:00.005 | exec-portfolio-metrics-analysis | at javax.security.auth.login.LoginContext.invoke(LoginContext.java:755)

  | December 11th 2018, 07:00:00.005 | exec-portfolio-metrics-analysis | at javax.security.auth.login.LoginContext.access$000(LoginContext.java:195)

  | December 11th 2018, 07:00:00.005 | exec-portfolio-metrics-analysis | at javax.security.auth.login.LoginContext$4.run(LoginContext.java:682)

  | December 11th 2018, 07:00:00.005 | exec-portfolio-metrics-analysis | at javax.security.auth.login.LoginContext$4.run(LoginContext.java:680)

  | December 11th 2018, 07:00:00.005 | exec-portfolio-metrics-analysis | at java.security.AccessController.doPrivileged(Native Method)

  | December 11th 2018, 07:00:00.005 | exec-portfolio-metrics-analysis | at javax.security.auth.login.LoginContext.invokePriv(LoginContext.java:680)

  | December 11th 2018, 07:00:00.005 | exec-portfolio-metrics-analysis | at javax.security.auth.login.LoginContext.login(LoginContext.java:587)

  | December 11th 2018, 07:00:00.005 | exec-portfolio-metrics-analysis | at org.apache.hadoop.security.UserGroupInformation.loginUserFromSubject(UserGroupInformation.java:797)

  | December 11th 2018, 07:00:00.005 | exec-portfolio-metrics-analysis | at org.apache.hadoop.security.UserGroupInformation.getLoginUser(UserGroupInformation.java:774)

  | December 11th 2018, 07:00:00.005 | exec-portfolio-metrics-analysis | at org.apache.hadoop.security.UserGroupInformation.getCurrentUser(UserGroupInformation.java:647)

  | December 11th 2018, 07:00:00.005 | exec-portfolio-metrics-analysis | at org.apache.spark.util.Utils$$anonfun$getCurrentUserName$1.apply(Utils.scala:2430)

  | December 11th 2018, 07:00:00.005 | exec-portfolio-metrics-analysis | at org.apache.spark.util.Utils$$anonfun$getCurrentUserName$1.apply(Utils.scala:2430)

  | December 11th 2018, 07:00:00.005 | exec-portfolio-metrics-analysis | at scala.Option.getOrElse(Option.scala:121)

  | December 11th 2018, 07:00:00.005 | exec-portfolio-metrics-analysis | at org.apache.spark.util.Utils$.getCurrentUserName(Utils.scala:2430)

  | December 11th 2018, 07:00:00.005 | exec-portfolio-metrics-analysis | at org.apache.spark.SparkContext.<init>(SparkContext.scala:295)

  | December 11th 2018, 07:00:00.002 | exec-portfolio-metrics-analysis | 2018-12-11 05:00:00.000  INFO 7 --- [taskScheduler-1] c.c.d.exec.collector.PortfolioCollector  : Running Hygieia EXEC Collector

See the parts in **BOLD**:

1. Failure to login where? 
2. Failure to login to what? 
2. Where is name being set? 

In the execcollector property file I also attempted the credentials for a dashboard user in DevOps db but to no avail. 

After some research I found that the execcollector working correctly Hygieia Exec Dashboard is subject to having run the hpsm collector in Hygieia Devops Dashboard.

But I'd like to understand why the collector is giving a Failure to login error? What is it failing to login to? and where the value name is being set?

Any direction to source code will also be very helpful.

Thank you :)

**Comment by Sbrenthughes** [comment]
@Leon-Africa Can you update to latest and try again?

**Comment by Sbrenthughes** [comment]
Closing due to no response.
