### ISSUE TITLE
Using Executive Dashboard without hpsm collector (or an alternative)

### ISSUE THREAD

**Issue by Leon-Africa** [Hygieia/ExecDashboard#28]
Hello,

Thank you for the great project.

I have found that a requirement to having the Executive Dashboard setup property is to have ran the hpsm collector (https://hygieia.github.io/Hygieia/hpsm.html) on the Hygieia Devops Dashboard.

1. Is there any possible work around to using the Exec Dashboard without using hpsm?
2. Where in the source code can we find this dependency on hpsm? (Both in DevOps and Exec Dashboard)
3. If we are using a different software to hpsm - if we were to write a collector for it is there any rules that need to be followed with respect to its ability to avail data to be used by Hygieia Exec? (aside from what is mentioned here https://hygieia.github.io/Hygieia/create_collector.html)

Any direction to source code will also be very helpful.

Thank you :)

**Comment by anobleperson** [comment]
It's not a requirement, however you'll need to find a way to get the equivalent data into the database, either with manual entry (yuck!) or you're own collector.  Apparently there is a workaround that imports a spreadsheet of information that the Hygieia team might be able to provide.

**Comment by Leon-Africa** [comment]
@anobleperson Thanks! Have you perhaps heard from the Hygiea Team concerning this? Have not been able to see where in the source code this is happening.

Closest assumption would be hear: https://github.com/Hygieia/ExecDashboard/blob/master/exec-analysis/src/main/java/com/capitalone/dashboard/exec/collector/HygieiaSparkConnection.java

For own collector assume maybe use Service Now: https://www.servicenow.com/products/servicenow-platform/configuration-management-database.html

Not really sure where else to look

**Comment by Sbrenthughes** [comment]
Here is a brief explanation of the data required and how to tie it to the dashboard: https://github.com/Hygieia/ExecDashboard/issues/19#issuecomment-465274851

If you copy and paste those two entires into your cmdb collection and tie them to a team dashboard as described, it will work.

**Comment by Leon-Africa** [comment]
@Sbrenthughes  Thanks!

**Comment by Sbrenthughes** [comment]
@Leon-Africa I am closing this for now. Please reopen if you have any further questions. You can also reach out to me on gitter.
