### ISSUE TITLE
exec-ui build error related to node-sass version

### ISSUE THREAD

**Issue by JackDGriffith** [Hygieia/ExecDashboard#29]
I am trying to build using the source I just downloaded however I'm getting an error:
[INFO] Downloading binary from https://github.com/sass/node-sass/releases/download/v4.5.3/win32-x64-59_binding.node
[ERROR] Cannot download "https://github.com/sass/node-sass/releases/download/v4.5.3/win32-x64-59_binding.node":
[ERROR]
[ERROR] HTTP error 404 Not Found
Looking on github it looks like the oldest version available currently is 4.9.0.

**Comment by JackDGriffith** [comment]
Found my issue was using too new of a version of nodejs apparently.

**Comment by amateus1** [comment]
try:
npm install --unsafe-perm node-sass
