### ISSUE TITLE
ExecDashboard

### ISSUE THREAD

**Issue by KalhariL** [Hygieia/ExecDashboard#32]
ExecDashboard is supposed to display following 9 matrices

1. Code Commits
2. Open Source Violations
3. Security Violations
4. Automated Tests Passing
5. Code Analysis Issues
6. Production Incidents
7. Unit Test Coverage
8. Production Releases
9. Average Pipeline Lead Time

But only 4 are displayed

1. Code Commits
2. Production Incidents
3. Open Source Violations
4. Code Analysis Issues

Remaining KPIs are commented out in UI. Can we uncomment it and use them without an issue? Are they commented due to them being invalid/incorrect in some way?
\exec-ui\src\app\modules\metrics\modules\previews\components\metric-previews\metric-previews.component.html

**Comment by tabladrum** [comment]
We are testing and redesigning many of these. Soon to be updated. Please stay tuned.

**Comment by KalhariL** [comment]
I see :) Thanks for the reply.  The matrices I'm interested are Average Pipeline Lead Time & Unit Test Coverage and also there are couple of custom KPIs as well. Would you like to email me the collectors for those two? May be I can work with you & contribute as well.

**Comment by hijmenf** [comment]
Is there an ETA on this? We would like to know for how long we should "stay tuned", so we can decide if we should start building these features on our own.

**Comment by Sbrenthughes** [comment]
7 has been added and a PR for 3 is waiting for review

**Comment by Sbrenthughes** [comment]
3 has been merged.

**Comment by DarrenClintAlbertyn** [comment]
@KalhariL  Hi have you attempted to rebuild the Executive Dashboard and retrieve the following KPI metrics

- Average Pipeline Lead Time
- Automated Tests Passing

TIA
