### ISSUE TITLE
CORS policy: No 'Access-Control-Allow-Origin' error at browser

### ISSUE THREAD

**Issue by Booma-Baskaran** [Hygieia/ExecDashboard#49]
Hi,

I am getting "Access to XMLHttpRequest at 'http://localhost:8080/api/portfolio' from origin 'http://localhost:4200' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource." error in the browser.

Any idea why I am getting this error? What is the solution?

Thanks,
Booma Baskaran.

**Comment by Sbrenthughes** [comment]
What command did you use to start it?

**Comment by Sbrenthughes** [comment]
@Booma-Baskaran any update?

**Comment by Booma-Baskaran** [comment]
@Sbrenthughes - It's fixed by having the correct apiUrl in environment.ts and environment.local.ts.
