### ISSUE TITLE
Version 2.* or 3.* ???

### ISSUE THREAD

**Issue by Mortagne** [Hygieia/ExecDashboard#5]
Hi,

i am not sure the difference between this version 3.* of ExecDashboard ....
vs the version 2.* ...

it's better to upgrade to the latest version ?

**Comment by matthewbeasley** [comment]
Hi @Mortagne - version 3.x is a new product that groups data collected by version 2.x allowing you to easily see data collected by multiple products. It's intended for executives to have a quick view into the CI/CD health of the portfolio of products they are responsible for. You'll want to keep your existing 2.x stack in place and stand up 3.x (ExecDashboard) alongside.

**Comment by venkiradkris** [comment]
Hi - I am planning to explore Hygieia 3.

Earlier version of Hygieia has following Mongo DB connected (**dashboarddb**).
dbname=dashboarddb
dbusername=dashboarduser
dbpassword=dbpassword

For Hygieia 3 as per instruction, i will be creating new Mongo DB (**analyticsdb**) with dbusername=dashboarduser, dbpassword=dbpassword.

[1] Hence In API Properties File For Hygieia 3, I need to give following DB Configuration. Hope i am correct. **Please confirm**.
dbname=analyticsdb
dbusername=dashboarduser
dbpassword=dbpassword

[2] For Collector application.properties in Hygieia 3, please validate/clarify following understanding.
dbname=analyticsdb 
Am i correct?

dbusername=dashboarduser 
Am i correct?

dbpassword=dbpassword 
Am i correct?

dbhostport=hostname:port 
Is this for DB details where analyticsdb is running? or is this for dashboarddb?

portfolio.readUriUserName= 
Do we need to leave it blank? OR what exactly is this user name?

portfolio.readUriPassword= 
Do we need to leave it blank? OR what exactly is this password?

portfolio.readUriDatabase=hostname:port
Is this for DB details of analyticsdb or dashboarddb?

portfolio.readUriPrefix=mongodb
Do we need to hard code as 'mongodb'?

portfolio.readDatabase=db_name
Is this DB Name of analyticsdb or dashboarddb?

portfolio.writeUri=mongodb://hostname:port
Is this for DB Details of analyticsdb or dashboarddb?

portfolio.writeDatabase=db_name
Is this DB Name of analyticsdb or dashboarddb?

Regards
Venkat

**Comment by venkiradkris** [comment]
[3]  I am getting build issue # 1. Even after installing required dependencies again and again, same issues are repeating.

[INFO] Running 'npm install --proxy=http://www-proxy-idc.in.oracle.com:80' in /usr/share/Hygieia3/exec-ui
[ERROR] npm WARN @angular/animations@4.4.7 requires a peer of @angular/core@4.4.7 but none is installed. You must install peer dependencies yourself.
[ERROR] npm WARN @angular/compiler@4.4.7 requires a peer of @angular/core@4.4.7 but none is installed. You must install peer dependencies yourself.
[ERROR] npm WARN @angular/compiler-cli@4.4.7 requires a peer of @angular/core@4.4.7 but none is installed. You must install peer dependencies yourself.
[ERROR] npm WARN @angular/core@2.4.10 requires a peer of zone.js@^0.7.2 but none is installed. You must install peer dependencies yourself.
[ERROR] npm WARN @angular/flex-layout@2.0.0-rc.1 requires a peer of zone.js@^0.7.2 but none is installed. You must install peer dependencies yourself.
[ERROR] npm WARN @angular/forms@4.4.7 requires a peer of @angular/core@4.4.7 but none is installed. You must install peer dependencies yourself.
[ERROR] npm WARN @angular/forms@4.4.7 requires a peer of @angular/common@4.4.7 but none is installed. You must install peer dependencies yourself.
[ERROR] npm WARN @angular/http@4.4.7 requires a peer of @angular/core@4.4.7 but none is installed. You must install peer dependencies yourself.
[ERROR] npm WARN @angular/platform-browser@4.4.7 requires a peer of @angular/core@4.4.7 but none is installed. You must install peer dependencies yourself.
[ERROR] npm WARN @angular/platform-browser@4.4.7 requires a peer of @angular/common@4.4.7 but none is installed. You must install peer dependencies yourself.
[INFO] up to date in 6.91s
[ERROR] npm WARN @angular/platform-browser-dynamic@4.4.7 requires a peer of @angular/core@4.4.7 but none is installed. You must install peer dependencies yourself.
[ERROR] npm WARN @angular/platform-browser-dynamic@4.4.7 requires a peer of @angular/common@4.4.7 but none is installed. You must install peer dependencies yourself.
[ERROR] npm WARN @angular/router@4.4.7 requires a peer of @angular/core@4.4.7 but none is installed. You must install peer dependencies yourself.
[ERROR] npm WARN @angular/router@4.4.7 requires a peer of @angular/common@4.4.7 but none is installed. You must install peer dependencies yourself.
[ERROR] npm WARN ngx-cookie@2.0.1 requires a peer of @angular/core@>=4.0.0 || >=5.0.0 but none is installed. You must install peer dependencies yourself.
[ERROR] npm WARN ngx-cookie@2.0.1 requires a peer of @angular/common@>=4.0.0 || >=5.0.0 but none is installed. You must install peer dependencies yourself.
[ERROR] npm WARN ngx-cookie-service@1.0.10 requires a peer of @angular/core@>=4.0.0 but none is installed. You must install peer dependencies yourself.
[ERROR] npm WARN ngx-infinite-scroll@0.8.4 requires a peer of @angular/common@>= 4.0.0 but none is installed. You must install peer dependencies yourself.
[ERROR] npm WARN ngx-infinite-scroll@0.8.4 requires a peer of @angular/core@>= 4.0.0 but none is installed. You must install peer dependencies yourself.
[ERROR] npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.2 (node_modules/fsevents):
[ERROR] npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

[4]  I am getting build issue # 2. I dont see "assembly/bin.xml" in source code code. Where do i find the same? 

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-assembly-plugin:2.6:single (create-archive) on project exec-ui: Error reading assemblies: Error locating assembly descriptor: assembly/bin.xml
[ERROR]
[ERROR] [1] [INFO] Searching for file location: /usr/share/Hygieia3/exec-ui/assembly/bin.xml
[ERROR]
[ERROR] [2] [INFO] File: /usr/share/Hygieia3/exec-ui/assembly/bin.xml does not exist.
[ERROR]
[ERROR] [3] [INFO] File: /usr/share/Hygieia3/assembly/bin.xml does not exist.

Regards
Venkat

**Comment by venkiradkris** [comment]
[5] Please ignore Issues # 3 and # 4 mentioned above.

I am getting below issue when i execute "npm run local" command under "Step 4: Run the UI" mentioned in URL "https://hygieia.github.io/ExecDashboard/EXECUI_Setup.html".

**ISSUE**
The "@angular/compiler-cli" package was not properly installed. Error: TypeError: _angular_core.InjectionToken is not a constructor
Error: The "@angular/compiler-cli" package was not properly installed. Error: TypeError: _angular_core.InjectionToken is not a constructor
    at Object.<anonymous> (/usr/share/Hygieia3/exec-ui/node_modules/@ngtools/webpack/src/index.js:14:11)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/share/Hygieia3/exec-ui/node_modules/@angular/cli/tasks/eject.js:10:19)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)

"nvm install 8.9.1" does installation of node and npm. 

How about "ng serve" installation i.e how to install "@angular/compiler-cli" packages properly? 

Please guide. Thanks.

Regards
Venkat

**Comment by venkiradkris** [comment]
Hi

**Could you please help to answer for my queries above [1] & [2]?**

[3], [4], [5] - i have fixed it myself.

Regards
Venkat

**Comment by matthewbeasley** [comment]
@venkiradkris - you really should've opened a separate issue for questions unrelated to the original issue. 

For the api, you are correct.

For collector:

```
dbname=analyticsdb
Am i correct? 
- yes

dbusername=dashboarduser
Am i correct? 
- yes

dbpassword=dbpassword
Am i correct? 
- yes

dbhostport=hostname:port
Is this for DB details where analyticsdb is running? or is this for dashboarddb?
- analyticsdb

portfolio.readUriUserName=
Do we need to leave it blank? OR what exactly is this user name?
- blank

portfolio.readUriPassword=
Do we need to leave it blank? OR what exactly is this password?
- blank

portfolio.readUriDatabase=hostname:port
Is this for DB details of analyticsdb or dashboarddb?
- dashboarddb

portfolio.readUriPrefix=mongodb
Do we need to hard code as 'mongodb'?
- yes this needs to be mongodb

portfolio.readDatabase=db_name
Is this DB Name of analyticsdb or dashboarddb?
- dashboarddb

portfolio.writeUri=mongodb://hostname:port
Is this for DB Details of analyticsdb or dashboarddb?
- analyticsdb

portfolio.writeDatabase=db_name
Is this DB Name of analyticsdb or dashboarddb?
- analyticsdb
```

**Comment by venkiradkris** [comment]
Thanks.
