### ISSUE TITLE
Execution dashboard failing in UI Phase

### ISSUE THREAD

**Issue by mitunmbj** [Hygieia/ExecDashboard#56]
[root@hygieia exec-ui]# npm run local

> hygieia-executive@0.0.0 local /home/mitun/git/ExecDashboard/exec-ui
> ng serve --host=0.0.0.0 --port=4200 --proxy-config=proxy.config.json --env=local

** NG Live Development Server is listening on 0.0.0.0:4200, open your browser on http://localhost:4200/ **
 10% building modules 3/3 modules 0 active[HPM] Proxy created: /api  ->  http://localhost:8081/api
[HPM] Proxy rewrite rule created: "^/api" ~> "http://localhost:8081/api"
[HPM] Subscribed to http-proxy events:  [ 'error', 'close' ]
Date: 2019-05-17T12:16:31.008Z                                                          
Hash: 580e98299e7cd206f4ff
Time: 107453ms
chunk {inline} inline.bundle.js, inline.bundle.js.map (inline) 5.83 kB [entry] [rendered]
chunk {main} main.bundle.js, main.bundle.js.map (main) 1.07 MB {vendor} [initial] [rendered]
chunk {polyfills} polyfills.bundle.js, polyfills.bundle.js.map (polyfills) 234 kB {inline} [initial] [rendered]
chunk {styles} styles.bundle.js, styles.bundle.js.map (styles) 10.4 kB {inline} [initial] [rendered]
chunk {vendor} vendor.bundle.js, vendor.bundle.js.map (vendor) 4.36 MB [initial] [rendered]

ERROR in ./node_modules/css-loader?{"sourceMap":false,"importLoaders":1}!./node_modules/postcss-loader?{"ident":"postcss"}!./node_modules/sass-loader/lib/loader.js?{"sourceMap":false,"precision":8,"includePaths":[]}!./src/assets/styles/styles.scss
Module build failed: Error: ENOENT: no such file or directory, scandir '/home/mitun/git/ExecDashboard/exec-ui/node_modules/node-sass/vendor'
    at Object.fs.readdirSync (fs.js:904:18)
    at Object.getInstalledBinaries (/home/mitun/git/ExecDashboard/exec-ui/node_modules/node-sass/lib/extensions.js:124:13)
    at foundBinariesList (/home/mitun/git/ExecDashboard/exec-ui/node_modules/node-sass/lib/errors.js:20:15)
    at foundBinaries (/home/mitun/git/ExecDashboard/exec-ui/node_modules/node-sass/lib/errors.js:15:5)
    at Object.module.exports.missingBinary (/home/mitun/git/ExecDashboard/exec-ui/node_modules/node-sass/lib/errors.js:45:5)
    at module.exports (/home/mitun/git/ExecDashboard/exec-ui/node_modules/node-sass/lib/binding.js:15:30)
    at Object.<anonymous> (/home/mitun/git/ExecDashboard/exec-ui/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/mitun/git/ExecDashboard/exec-ui/node_modules/sass-loader/lib/loader.js:3:14)
    at Module._compile (module.js:635:30)
 @ ./src/assets/styles/styles.scss 4:14-205
 @ multi ./src/assets/styles/styles.scss
....
....

**Comment by mitunmbj** [comment]
The mvn build too marks failure
PLZ Do paste the actual installation and configuration steps to fix it

**Comment by Sbrenthughes** [comment]
can you navigate to the exec-ui folder and `run npm install`?

**Comment by mitunmbj** [comment]
@Sbrenthughes i ran npm install and then ran npm run local but npm run local cause failure stating any build failures 
when i ran mvn clean install in ExecutiveDashboard directory then too build is marked as failure in  ui phase

**Comment by mitunmbj** [comment]
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] com.capitalone.dashboard:HygieiaExec 1.0.0-SNAPSHOT  SUCCESS [  8.583 s]
[INFO] com.capitalone.dashboard:exec-core ................. SUCCESS [ 49.539 s]
[INFO] com.capitalone.dashboard:exec-analysis ............. SUCCESS [ 26.847 s]
[INFO] com.capitalone.dashboard:exec-api .................. SUCCESS [ 41.415 s]
[INFO] com.capitalone.dashboard:exec-ui 1.0.0-SNAPSHOT .... FAILURE [03:10 min]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 05:20 min
[INFO] Finished at: 2019-05-20T11:09:52+05:30
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:0.0.29:npm (npm run-script build) on project exec-ui: Failed to run task: 'npm run-script build' failed. (error code 1) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :exec-ui
[root@hygieia ExecDashboard]#

**Comment by Sbrenthughes** [comment]
What do you get when you run `npm run-script build` ?

**Comment by Sbrenthughes** [comment]
Also, what mvn version and node version are you using?

**Comment by Sbrenthughes** [comment]
What version of node are you using?

**Comment by Sbrenthughes** [comment]
Closing due to no update. Please reopen if issue persist
